### ISSUE TITLE
Use C++ CIPHER_KEY_SIZE as key size in `generate_symmetric_key`

### ISSUE THREAD

**Issue by chester-leung** [mc2-project/mc2#139]
To prevent inconsistent key sizes across the MC<sup>2</sup> ecosystem, we should not allow users to specify a key size in `generate_symmetric_key()`. Instead, we should retrieve the `CIPHER_KEY_SIZE` from C++, similar to [this](https://github.com/mc2-project/mc2/blob/master/python-package/mc2client/core.py#L521), and use the `CIPHER_KEY_SIZE` as the number of bytes for our generated key. 

To do so, we'll need to add a function in `src/c_api.cpp`, similar to the [`cipher_iv_size()` function](https://github.com/mc2-project/mc2/blob/master/src/c_api.cpp#L16) that gets the `CIPHER_KEY_SIZE` from C++.

**Comment by chester-leung** [comment]
Hi @lvntky, that would be great!

**Comment by lvntky** [comment]
@chester-leung sorry for the delay I've been busy for few days at my job and can't log in to GitHub. now I'm forked the project, I'm working on it. I hope I can figure it out, Best wishes!
