### ISSUE TITLE
No module named 'fxgb_pb2'

### ISSUE THREAD

**Issue by hacql2004** [mc2-project/mc2#23]
Hi, thanks for your sharing.
I followed your instruction, while met an error as below.
![image](https://user-images.githubusercontent.com/21165759/76758166-25951680-67c4-11ea-9980-607ca549000f.png)
Could u help me to figure out this? Thanks in advance.

**Comment by chester-leung** [comment]
Hi @hacql2004 

In `dmlc-core/tracker/dmlc_tracker` do you see a file named `fxgb_pb2.py`? If so, please set your PYTHONPATH to `/path/to/dmlc-core/tracker/dmlc_tracker`. 

```
export PYTHONPATH=/path/to/dmlc-core/tracker/dmlc_tracker
```

**Comment by hacql2004** [comment]
It works, thanks.
