### ISSUE TITLE
what's the difference between mc2-xgboost and secure-xgboost

### ISSUE THREAD

**Issue by hacql2004** [mc2-project/mc2#24]
Hi, when I git down your project by "git clone --recursive https://github.com/mc2-project/mc2.git". It seems that there's only mc2-xgboost in this git repo, but not secure-xgboost. (To better continue, I still git it from another git repo. ) Is there any difference between mc2-xgboost and secure-xgboost here?
Thanks.

**Comment by chester-leung** [comment]
mc2-xgboost is our cleaner, up to date version of secure-xgboost. 

secure-xgboost is no longer being maintained, but should suffice for now for use with Federated XGBoost. We'll soon refactor our codebase such that Federated XGBoost no longer depends on secure-xgboost.

**Comment by hacql2004** [comment]
Great, look forward to it.
