### ISSUE TITLE
Can't find secure-xgboost module

### ISSUE THREAD

**Issue by qingwh** [mc2-project/mc2#34]
Hi,
 I conducted the following steps for federated learning:
git clone --recursive https://github.com/mc2-project/mc2.git
cd mc2/secure-xgboost

I can't find secure-xgboost module in mc2. Thanks!

**Comment by podcastinator** [comment]
Hi, I think you mean to do:
`cd mc2/mc2-xgboost`

Also, the documentation for the `mc2-xgboost` sub-project can be found here: https://mc2-xgboost.readthedocs.io/en/latest/

**Comment by qingwh** [comment]
Hi, When I conducted federated xgboost, do I need to install secure-xgboost first, using the following link's steps?
https://mc2-xgboost.readthedocs.io/en/latest/build.html#installing-secure-xgboost-dependencies
