### ISSUE TITLE
Federated XGBoost installation questions

### ISSUE THREAD

**Issue by qingwh** [mc2-project/mc2#35]
Hi, When I conducted federated xgboost, do I need to install secure-xgboost first, using the following link's steps?
https://mc2-xgboost.readthedocs.io/en/latest/build.html#installing-secure-xgboost-dependencies

**Comment by chester-leung** [comment]
Hi @qingwh, thanks for your patience. We've reorganized the repo, and there's now [a separate repository for Federated XGBoost](https://github.com/mc2-project/federated-xgboost) that is separate from [MC^2 XGBoost](https://github.com/mc2-project/mc2-xgboost) (Secure XGBoost). 

There are installation instructions and quickstart instructions in the README of Federated XGBoost. Hope this helps!
