### ISSUE TITLE
Host_IP and file_path 

### ISSUE THREAD

**Issue by skb888** [mc2-project/mc2#4]
Hey guys, I follow your guys readme file to execute the federated xgboost. While, I encounter some problems.
Question1: If the hosts.config should be under the sample folder? Meanwhile, I will run ./start_job.sh this script under the sample folder since I see ../../ at the bottom of this script(run scripts in dmlc-core this folder. Also, is there necessary to include start_job.sh and hosts.config under federated-xgboost folder?
Question2: In my understand, different clients dataset will locate in their own local node. Here, they probably need to have the same file names (eg: train.csv, test.csv). In may case, I launch three different servers in the virtualbox. Thus, they can not have the same file path as the tracker(I treat it as my local machine as the master). Hence, I am not sure whether I can use relative path such as 
fxgb.load_training_data('../../data/train.csv') instead of your guys fxgb.load_training_data('home/ubuntu/mc2/data/train.csv'). 
Question3: As I mention before, I use virtualbox to launch three servers as worker nodes. I encounter the error:  File "/Users/shi/Desktop/mc2/dmlc-core/tracker/dmlc_tracker/tracker.py", line 416, in get_host_ip
    hostIP = socket.gethostbyname(socket.gethostname())
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
Do you guys have any idea how to solve this issue? i include 192.168.56.101 and other two host ips in hosts.config.
Thanks Guys.

**Comment by chester-leung** [comment]
1. `hosts.config` should also be in the sample folder. Looks like it was missing before. I've updated the repo to reflect this change. 
It's not necessary to have `start_job.sh` and `hosts.config` in the `federated-xgboost` directory, but you should have them in `federated-xgboost/sample/`.

2. You should be able to use the relative path. 

3. This error may be a result of not having the `hosts.config` file in the `sample/` directory. Once you place it in there, with the file containing the IPs and ports of your workers, it should work. Let me know if you've already done this and it doesn't work.

**Comment by skb888** [comment]
Thanks for the clarification. I still encounter the host error as before that get_host_ip
hostIP = socket.gethostbyname(socket.gethostname()).  I just put my three workers IPs and ports in three separate lines in hosts.config under sample folder.  I also double check that the master node's public key has been put in to different worker nodes.
The error seems come from the dmlc-core/tracker/dmlc-tracker/tracker.py that it can not find IPs when I submit the task.
